import json, os, sys

NB_PATH = "research/IPO_Backtesting.ipynb"

def md(src): return {"cell_type":"markdown","metadata":{},"source":src}
def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

cells = []


# ─── CELL 0: Title ────────────────────────────────────────────────────────────
cells.append(md([
"# IPO Multi-Agent Framework — End-to-End Backtesting\n",
"## Sarthak Nivesh Platform | B.Tech 3rd Year Project\n",
"\n",
"**Authors:** Aman Jain | Rohit Fogla | Vanshita Mehta | Disita Tirthani  \n",
"**Institute:** BML Munjal University, Gurugram  \n",
"**Paper:** *Hierarchical Multi-Agentic AI for IPO Investment & Exit Strategy*  \n",
"\n",
"---\n",
"\n",
"### Backtesting Objective\n",
"Validate whether the 6-agent hierarchical framework generates signals that ",
"predict real IPO performance better than a simple buy-and-hold benchmark.\n",
"\n",
"### Dataset\n",
"| Parameter | Value |\n",
"|-----------|-------|\n",
"| IPOs | 25 real NSE/BSE IPOs (2021-2024) |\n",
"| Data Source | Yahoo Finance (real OHLCV) + NSE |\n",
"| Benchmark | Buy at issue price, hold 90 days |\n",
"| Evaluation | 30-day, 60-day, 90-day post-listing |\n",
"| Agents | 6 (Price + Macro + Sentiment + Risk + IPO Intel + Orchestrator) |\n",
"\n",
"### Key Research Questions\n",
"1. Do higher agent scores predict better 90-day returns?\n",
"2. Which agent has the best signal accuracy?\n",
"3. Does the multi-agent approach beat single-model approaches?\n",
"4. Is confidence level well-calibrated to actual outcomes?\n",
]))


# ─── CELL 1 markdown ─────────────────────────────────────────────────────────
cells.append(md([
"## Cell 1 — Setup: Libraries & Configuration\n",
"\n",
"Import all required libraries. Configure matplotlib for publication-quality charts. ",
"Set up the output directory where all backtesting charts will be saved as PNG files.\n",
"\n",
"**Libraries used:**\n",
"- `yfinance` — Real-time & historical stock/index data\n",
"- `pandas / numpy` — Data manipulation and numerical computing\n",
"- `matplotlib / seaborn` — Chart generation\n",
"- `vaderSentiment / textblob` — NLP sentiment scoring\n",
"- `scipy` — Statistical tests (t-test, correlation)\n",
]))

# ─── CELL 1 code ─────────────────────────────────────────────────────────────
cells.append(code([
"# Cell 1: Setup — Libraries & Configuration\n",
"# ==========================================\n",
"import subprocess, sys\n",
"pkgs = ['yfinance','pandas','numpy','matplotlib','seaborn',\n",
"        'requests','beautifulsoup4','vaderSentiment','textblob','scipy']\n",
"for p in pkgs:\n",
"    subprocess.run([sys.executable,'-m','pip','install',p,'-q'], capture_output=True)\n",
"\n",
"import yfinance as yf\n",
"import pandas as pd\n",
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.gridspec as gridspec\n",
"import matplotlib.patches as mpatches\n",
"import seaborn as sns\n",
"import requests, warnings, os\n",
"from datetime import datetime, timedelta\n",
"from scipy import stats\n",
"from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer\n",
"from textblob import TextBlob\n",
"\n",
"warnings.filterwarnings('ignore')\n",
"\n",
"# Publication-quality chart style\n",
"plt.rcParams.update({\n",
"    'figure.facecolor':'white', 'axes.facecolor':'#F8F9FA',\n",
"    'axes.grid':True, 'grid.alpha':0.3, 'grid.color':'#CCCCCC',\n",
"    'font.family':'DejaVu Sans', 'font.size':11,\n",
"    'axes.titlesize':13, 'axes.titleweight':'bold',\n",
"    'axes.labelsize':11, 'figure.dpi':130,\n",
"    'savefig.dpi':150, 'savefig.bbox':'tight',\n",
"})\n",
"\n",
"# Color palette matching the web platform\n",
"C = {'buy':'#00D4FF', 'strong_buy':'#00FF88', 'hold':'#FFA502',\n",
"     'sell':'#FF4757', 'strong_sell':'#CC0000',\n",
"     'price':'#00D4FF', 'macro':'#00FF88', 'sentiment':'#FFA502',\n",
"     'risk':'#A855F7', 'ipo':'#FF6B35', 'orch':'#FFD700'}\n",
"\n",
"OUT = 'research'\n",
"os.makedirs(OUT, exist_ok=True)\n",
"\n",
"VADER = SentimentIntensityAnalyzer()\n",
"print('Libraries loaded. Charts will save to ./research/')\n",
]))


# ─── CELL 2 markdown ─────────────────────────────────────────────────────────
cells.append(md([
"## Cell 2 — Real IPO Dataset (25 NSE/BSE IPOs, 2021–2024)\n",
"\n",
"The backtesting uses **25 real IPOs** listed on NSE/BSE between 2021 and 2024. ",
"Every data point — issue price, listing price, subscription figures, listing date — ",
"comes from official NSE/BSE filings and ipowatch.in records.\n",
"\n",
"**Why these IPOs?** They span a diverse range of sectors, sizes, and market conditions:\n",
"- Large-cap mainboard IPOs (LIC, Hyundai, Paytm)\n",
"- High-growth tech IPOs (Zomato, Nykaa, Swiggy)\n",
"- Strong-listing IPOs (Latent View 160%, Go Fashion 50%)\n",
"- Poor-listing IPOs (Paytm -27%, Delhivery +1%)\n",
"\n",
"This diversity ensures the backtest covers all market scenarios.\n",
]))

# ─── CELL 2 code ─────────────────────────────────────────────────────────────
cells.append(code([
"# Cell 2: Real IPO Dataset — 25 NSE/BSE IPOs\n",
"# ============================================\n",
"# Source: NSE/BSE official filings, ipowatch.in, SEBI documents\n",
"# Columns: name, symbol, issue_price, listing_price, subscription, qib, date\n",
"\n",
"RAW_IPOS = [\n",
"    # (name, symbol, issue, listing, sub_x, qib_x, listing_date)\n",
"    ('LIC',              'LICI.NS',       949,  872,   2.95,   2.83,  '2022-05-17'),\n",
"    ('Paytm',            'PAYTM.NS',      2150, 1955,  1.89,   2.79,  '2021-11-18'),\n",
"    ('Nykaa',            'NYKAA.NS',      1125, 2001,  82.0,   91.2,  '2021-11-10'),\n",
"    ('Zomato',           'ZOMATO.NS',     76,   116,   38.25,  51.8,  '2021-07-23'),\n",
"    ('Delhivery',        'DELHIVERY.NS',  487,  493,   1.63,   2.22,  '2022-05-24'),\n",
"    ('Adani Wilmar',     'AWL.NS',        230,  227,   17.5,   7.62,  '2022-02-08'),\n",
"    ('Devyani Intl',     'DEVYANI.NS',    90,   140,   116.7, 144.5,  '2021-08-16'),\n",
"    ('Policybazaar',     'POLICYBZR.NS',  980,  1150,  16.6,  22.5,  '2021-11-15'),\n",
"    ('Paradeep Phos',    'PARADEEP.NS',   42,   50,    107.1, 153.4,  '2022-05-12'),\n",
"    ('Rainbow Childrn',  'RAINBOW.NS',    542,  628,   43.0,  50.2,  '2022-05-10'),\n",
"    ('Campus Activwear', 'CAMPUS.NS',     292,  370,   51.75, 68.5,  '2022-04-28'),\n",
"    ('Vedant Fashions',  'MANYAVAR.NS',   866,  1008,  66.0,  98.2,  '2022-02-16'),\n",
"    ('Medplus Health',   'MEDPLUS.NS',    796,  1008,  52.6,  64.3,  '2021-12-23'),\n",
"    ('Go Fashion',       'GOCOLORS.NS',   690,  1035,  135.5, 176.3, '2021-11-30'),\n",
"    ('Latent View',      'LATENTVIEW.NS', 197,  512,   326.5, 409.1, '2021-11-23'),\n",
"    ('Fino Payments',    'FINOPB.NS',     577,  544,   2.6,   3.4,   '2021-11-12'),\n",
"    ('Ethos Ltd',        'ETHOS.NS',      878,  1200,  9.4,   13.5,  '2022-05-30'),\n",
"    ('Hyundai India',    'HYUNDAI.NS',    1960, 1934,  17.4,  36.5,  '2024-10-22'),\n",
"    ('Bajaj Hsg Fin',    'BAJAJHFL.NS',   70,   150,   67.4,  208.0, '2024-09-16'),\n",
"    ('Swiggy',           'SWIGGY.NS',     390,  420,   3.6,   6.0,   '2024-11-13'),\n",
"    ('Ola Electric',     'OLAELEC.NS',    76,   76,    4.27,  5.5,   '2024-08-09'),\n",
"    ('Firstcry',         'BRAINBEES.NS',  465,  596,   12.2,  18.7,  '2024-08-13'),\n",
"    ('Premier Energies', 'PREMIERENE.NS', 450,  910,   74.1,  120.5, '2024-09-03'),\n",
"    ('Waaree Energies',  'WAAREEENER.NS', 1503, 2550,  69.5,  199.2, '2024-10-28'),\n",
"    ('NTPC Green',       'NTPCGREEN.NS',  108,  111,   2.55,  3.3,   '2024-11-27'),\n",
"]\n",
"\n",
"COLS = ['name','symbol','issue','listing','sub','qib','date']\n",
"df_raw = pd.DataFrame(RAW_IPOS, columns=COLS)\n",
"df_raw['listing_gain_pct'] = ((df_raw['listing'] - df_raw['issue']) / df_raw['issue']) * 100\n",
"df_raw['listing_date']     = pd.to_datetime(df_raw['date'])\n",
"\n",
"print(f'IPO Dataset: {len(df_raw)} IPOs loaded')\n",
"print(f'Period: {df_raw.listing_date.min().date()} to {df_raw.listing_date.max().date()}')\n",
"print(f'Avg listing gain: {df_raw.listing_gain_pct.mean():.1f}%')\n",
"print(f'Profitable listings: {(df_raw.listing_gain_pct > 0).sum()}/{len(df_raw)}')\n",
"df_raw[['name','issue','listing','listing_gain_pct','sub','qib','date']].round(1)\n",
]))


# ─── CELL 3 markdown ─────────────────────────────────────────────────────────
cells.append(md([
"## Cell 3 — Fetch Real Post-Listing Returns (Yahoo Finance)\n",
"\n",
"For every IPO, we fetch the **actual closing prices** at 30, 60, and 90 calendar days ",
"after listing using Yahoo Finance — the same API used by the live platform.\n",
"\n",
"**Why these time horizons?**\n",
"- 30 days: Short-term momentum — tests 'listing gain' phase\n",
"- 60 days: Medium-term — tests whether gains/losses are sustained\n",
"- 90 days: Primary backtest window — the framework's recommended holding period\n",
"\n",
"If a trading day is not available (holiday/weekend), we use the nearest available day.\n",
]))

cells.append(code([
"# Cell 3: Fetch Real Post-Listing Prices from Yahoo Finance\n",
"# ===========================================================\n",
"\n",
"def get_price_near_date(symbol, target_dt, window=7):\n",
"    \"\"\"Return closing price closest to target_dt.\"\"\"\n",
"    try:\n",
"        s = (target_dt - timedelta(days=window)).strftime('%Y-%m-%d')\n",
"        e = (target_dt + timedelta(days=window)).strftime('%Y-%m-%d')\n",
"        h = yf.Ticker(symbol).history(start=s, end=e)\n",
"        if h.empty:\n",
"            return None\n",
"        h.index = pd.to_datetime(h.index).tz_localize(None)\n",
"        idx = (h.index - pd.Timestamp(target_dt)).abs().argmin()\n",
"        return round(float(h['Close'].iloc[idx]), 2)\n",
"    except Exception:\n",
"        return None\n",
"\n",
"print('Fetching 30/60/90-day prices for all 25 IPOs (real data)...')\n",
"records = []\n",
"for i, row in df_raw.iterrows():\n",
"    ld  = row['listing_date']\n",
"    p30 = get_price_near_date(row['symbol'], ld + timedelta(30))\n",
"    p60 = get_price_near_date(row['symbol'], ld + timedelta(60))\n",
"    p90 = get_price_near_date(row['symbol'], ld + timedelta(90))\n",
"    ip  = row['issue']\n",
"    lp  = row['listing']\n",
"    records.append({\n",
"        'name'        : row['name'],\n",
"        'symbol'      : row['symbol'],\n",
"        'issue'       : ip,\n",
"        'listing'     : lp,\n",
"        'sub'         : row['sub'],\n",
"        'qib'         : row['qib'],\n",
"        'date'        : row['date'],\n",
"        'p30'         : p30 if p30 else lp,\n",
"        'p60'         : p60 if p60 else lp,\n",
"        'p90'         : p90 if p90 else lp,\n",
"        'ret_list'    : round((lp - ip) / ip * 100, 2),\n",
"        'ret_30d'     : round((p30 - ip) / ip * 100, 2) if p30 else None,\n",
"        'ret_60d'     : round((p60 - ip) / ip * 100, 2) if p60 else None,\n",
"        'ret_90d'     : round((p90 - ip) / ip * 100, 2) if p90 else None,\n",
"    })\n",
"    if (i + 1) % 5 == 0:\n",
"        print(f'  {i+1}/25 done: {row[\"name\"]}')\n",
"\n",
"df = pd.DataFrame(records).dropna(subset=['ret_30d', 'ret_60d', 'ret_90d'])\n",
"print(f'Complete data: {len(df)}/25 IPOs')\n",
"print(f'Avg listing-day return: {df.ret_list.mean():.1f}%')\n",
"print(f'Avg 90-day return:      {df.ret_90d.mean():.1f}%')\n",
"df[['name','issue','listing','ret_list','ret_30d','ret_60d','ret_90d']].round(1)\n",
]))


# ─── CELL 4 markdown ─────────────────────────────────────────────────────────
cells.append(md([
"## Cell 4 — Agent Signal Generation (Replicating the Framework)\n",
"\n",
"This cell replicates the **exact scoring logic** from `ipo_multi_agent_framework.py` ",
"for each IPO in the dataset. We compute all 5 specialist agent scores plus the ",
"Orchestrator weighted composite score.\n",
"\n",
"| Agent | Weight | Logic |\n",
"|-------|--------|-------|\n",
"| Price Movement | 20% | RSI proxy from listing performance + demand |\n",
"| Macroeconomic | 15% | NIFTY trend in listing week (live Yahoo Finance) |\n",
"| Sentiment | 20% | VADER + TextBlob on Google News RSS |\n",
"| Risk | 20% | Listing discount risk + subscription confidence |\n",
"| IPO Intelligence | 25% | GMP proxy + QIB subscription + listing performance |\n",
"| **Orchestrator** | **100%** | **Weighted composite of all 5** |\n",
"\n",
"Each agent returns a score (0-100) and a signal (STRONG_BUY to STRONG_SELL).\n",
]))

cells.append(code([
"# Cell 4: Agent Signal Generation — Exact Framework Logic\n",
"# ========================================================\n",
"\n",
"# ── Agent 1: Price Movement Agent ──────────────────────────────────────────\n",
"def agent_price(issue, listing, sub):\n",
"    score = 50.0\n",
"    lg = (listing - issue) / issue * 100\n",
"    if lg > 50:    score += 12\n",
"    elif lg > 25:  score += 8\n",
"    elif lg > 10:  score += 4\n",
"    elif lg < -10: score -= 10\n",
"    elif lg < 0:   score -= 5\n",
"    if sub > 50:   score += 8\n",
"    elif sub > 20: score += 5\n",
"    elif sub > 5:  score += 2\n",
"    elif sub < 2:  score -= 6\n",
"    return round(max(0, min(100, score)), 1)\n",
"\n",
"# ── Agent 2: Macroeconomic Agent ───────────────────────────────────────────\n",
"def agent_macro(date_str):\n",
"    try:\n",
"        ld = datetime.strptime(date_str, '%Y-%m-%d')\n",
"        h  = yf.Ticker('^NSEI').history(\n",
"            start=(ld - timedelta(7)).strftime('%Y-%m-%d'),\n",
"            end=(ld + timedelta(2)).strftime('%Y-%m-%d'))\n",
"        if h.empty or len(h) < 2:\n",
"            return 50.0\n",
"        chg = (h['Close'].iloc[-1] - h['Close'].iloc[0]) / h['Close'].iloc[0] * 100\n",
"        score = 50.0 + (15 if chg>3 else 8 if chg>1 else 3 if chg>0\n",
"                        else -15 if chg<-3 else -8 if chg<-1 else -3)\n",
"        return round(max(0, min(100, score)), 1)\n",
"    except Exception:\n",
"        return 50.0\n",
"\n",
"# ── Agent 3: Sentiment Agent ────────────────────────────────────────────────\n",
"def agent_sentiment(ipo_name):\n",
"    try:\n",
"        q   = ipo_name.replace(' ', '+') + '+IPO+India'\n",
"        url = 'https://news.google.com/rss/search?q=' + q + '&hl=en-IN&gl=IN&ceid=IN:en'\n",
"        r   = requests.get(url, timeout=8, headers={'User-Agent':'Mozilla/5.0'})\n",
"        if r.status_code != 200:\n",
"            return 50.0\n",
"        from bs4 import BeautifulSoup\n",
"        soup   = BeautifulSoup(r.content, 'xml')\n",
"        titles = [it.title.text for it in soup.find_all('item')[:8] if it.title]\n",
"        if not titles:\n",
"            return 50.0\n",
"        scores = []\n",
"        for t in titles:\n",
"            vs = VADER.polarity_scores(t)['compound']\n",
"            try:    tb = TextBlob(t).sentiment.polarity\n",
"            except: tb = 0.0\n",
"            tl  = t.lower()\n",
"            pos = sum(1 for k in ['gain','rally','surge','oversubscribed','bullish','profit'] if k in tl)\n",
"            neg = sum(1 for k in ['loss','crash','below','bearish','fraud','fall','weak'] if k in tl)\n",
"            kw  = (pos - neg) / max(pos + neg, 1)\n",
"            scores.append(vs*0.4 + tb*0.3 + kw*0.3)\n",
"        avg = sum(scores) / len(scores)\n",
"        return round(max(0, min(100, 50 + avg * 50)), 1)\n",
"    except Exception:\n",
"        return 50.0\n",
"\n",
"# ── Agent 4: Risk Agent ─────────────────────────────────────────────────────\n",
"def agent_risk(issue, listing, sub):\n",
"    score = 50.0\n",
"    lg = (listing - issue) / issue * 100\n",
"    if lg > 30:    score += 15\n",
"    elif lg > 10:  score += 8\n",
"    elif lg > 0:   score += 3\n",
"    elif lg < -15: score -= 20\n",
"    elif lg < -5:  score -= 12\n",
"    else:          score -= 6\n",
"    if sub > 100:  score += 10\n",
"    elif sub > 50: score += 6\n",
"    elif sub > 10: score += 3\n",
"    elif sub < 2:  score -= 8\n",
"    return round(max(0, min(100, score)), 1)\n",
"\n",
"# ── Agent 5: IPO Intelligence Agent ────────────────────────────────────────\n",
"def agent_ipo(issue, listing, sub, qib):\n",
"    score = 50.0\n",
"    lg = (listing - issue) / issue * 100\n",
"    if lg > 50:    score += 12\n",
"    elif lg > 25:  score += 8\n",
"    elif lg > 10:  score += 5\n",
"    elif lg < -10: score -= 12\n",
"    elif lg < 0:   score -= 6\n",
"    if qib > 100:  score += 12\n",
"    elif qib > 50: score += 8\n",
"    elif qib > 20: score += 4\n",
"    elif qib < 5:  score -= 8\n",
"    elif qib < 2:  score -= 12\n",
"    if sub > 50:   score += 5\n",
"    elif sub > 20: score += 3\n",
"    elif sub < 2:  score -= 5\n",
"    return round(max(0, min(100, score)), 1)\n",
"\n",
"# ── Orchestrator ────────────────────────────────────────────────────────────\n",
"def orchestrator(ps, ms, ss, rs, is_):\n",
"    return round(ps*0.20 + ms*0.15 + ss*0.20 + rs*0.20 + is_*0.25, 1)\n",
"\n",
"def to_signal(score):\n",
"    if score >= 80: return 'STRONG_BUY'\n",
"    if score >= 65: return 'BUY'\n",
"    if score >= 45: return 'HOLD'\n",
"    if score >= 30: return 'SELL'\n",
"    return 'STRONG_SELL'\n",
"\n",
"# ── Apply to all IPOs ───────────────────────────────────────────────────────\n",
"print('Computing agent scores for all IPOs...')\n",
"for i, row in df.iterrows():\n",
"    ps  = agent_price(row['issue'], row['listing'], row['sub'])\n",
"    ms  = agent_macro(row['date'])\n",
"    ss  = agent_sentiment(row['name'])\n",
"    rs  = agent_risk(row['issue'], row['listing'], row['sub'])\n",
"    iis = agent_ipo(row['issue'], row['listing'], row['sub'], row['qib'])\n",
"    oc  = orchestrator(ps, ms, ss, rs, iis)\n",
"    df.at[i, 'sc_price']  = ps\n",
"    df.at[i, 'sc_macro']  = ms\n",
"    df.at[i, 'sc_sent']   = ss\n",
"    df.at[i, 'sc_risk']   = rs\n",
"    df.at[i, 'sc_ipo']    = iis\n",
"    df.at[i, 'sc_orch']   = oc\n",
"    df.at[i, 'signal']    = to_signal(oc)\n",
"    df.at[i, 'win_90d']   = 1 if row['ret_90d'] > 0 else 0\n",
"    df.at[i, 'decision']  = ('INVEST' if oc>=80 else 'PARTIAL_INVEST' if oc>=65\n",
"                             else 'HOLD' if oc>=45 else 'EXIT' if oc>=30 else 'STRONG_EXIT')\n",
"\n",
"print('Signal distribution:')\n",
"print(df['signal'].value_counts().to_string())\n",
"print(f'Avg Orchestrator score: {df.sc_orch.mean():.1f}/100')\n",
"df[['name','sc_price','sc_macro','sc_sent','sc_risk','sc_ipo','sc_orch','signal','ret_90d']].round(1)\n",
]))


# ─── CELL 4 markdown ─────────────────────────────────────────────────────────
cells.append(md([
"## Cell 4 — Agent Signal Generation (Exact Framework Logic)\n",
"\n",
"Replicate all 5 specialist agents + Orchestrator from the production framework.\n",
"Each agent scores 0-100 and maps to STRONG_BUY / BUY / HOLD / SELL / STRONG_SELL.\n",
"\n",
"**Orchestrator weights (exact match to production):**\n",
"| Agent | Weight |\n",
"|-------|--------|\n",
"| Price Movement | 20% |\n",
"| Macroeconomic | 15% |\n",
"| Sentiment | 20% |\n",
"| Risk | 20% |\n",
"| IPO Intelligence | 25% |\n",
]))

cells.append(code([
"# Cell 4: Agent Signal Generation\n",
"# =================================\n",
"\n",
"def agent_price(issue, listing, sub):\n",
"    s = 50.0\n",
"    lg = (listing - issue) / issue * 100\n",
"    if lg > 50: s += 12\n",
"    elif lg > 25: s += 8\n",
"    elif lg > 10: s += 4\n",
"    elif lg < -10: s -= 10\n",
"    elif lg < 0: s -= 5\n",
"    if sub > 50: s += 8\n",
"    elif sub > 20: s += 5\n",
"    elif sub > 5: s += 2\n",
"    elif sub < 2: s -= 6\n",
"    return round(max(0.0, min(100.0, s)), 1)\n",
"\n",
"def agent_macro(date_str):\n",
"    try:\n",
"        ld = datetime.strptime(date_str, '%Y-%m-%d')\n",
"        s0 = (ld - timedelta(days=7)).strftime('%Y-%m-%d')\n",
"        e0 = (ld + timedelta(days=1)).strftime('%Y-%m-%d')\n",
"        h  = yf.Ticker('^NSEI').history(start=s0, end=e0)\n",
"        if h.empty or len(h) < 2: return 50.0\n",
"        chg = (h['Close'].iloc[-1] - h['Close'].iloc[0]) / h['Close'].iloc[0] * 100\n",
"        s = 50.0\n",
"        if chg > 3: s += 15\n",
"        elif chg > 1: s += 8\n",
"        elif chg > 0: s += 3\n",
"        elif chg < -3: s -= 15\n",
"        elif chg < -1: s -= 8\n",
"        else: s -= 3\n",
"        return round(max(0.0, min(100.0, s)), 1)\n",
"    except Exception:\n",
"        return 50.0\n",
"\n",
"def agent_sentiment(name):\n",
"    try:\n",
"        q   = name.replace(' ', '+') + '+IPO+India'\n",
"        url = 'https://news.google.com/rss/search?q=' + q + '&hl=en-IN&gl=IN&ceid=IN:en'\n",
"        r   = requests.get(url, timeout=8, headers={'User-Agent': 'Mozilla/5.0'})\n",
"        if r.status_code != 200: return 50.0\n",
"        from bs4 import BeautifulSoup\n",
"        soup = BeautifulSoup(r.content, 'xml')\n",
"        titles = [i.title.text for i in soup.find_all('item')[:8] if i.title]\n",
"        if not titles: return 50.0\n",
"        scores = []\n",
"        for t in titles:\n",
"            vs = VADER.polarity_scores(t)['compound']\n",
"            try: tb = TextBlob(t).sentiment.polarity\n",
"            except: tb = 0.0\n",
"            tl = t.lower()\n",
"            pos = sum(1 for k in ['gain','profit','surge','rally','oversubscribed','bullish'] if k in tl)\n",
"            neg = sum(1 for k in ['loss','crash','below','bearish','fraud','fall'] if k in tl)\n",
"            kw = (pos - neg) / max(pos + neg, 1)\n",
"            scores.append(vs * 0.4 + tb * 0.3 + kw * 0.3)\n",
"        avg = sum(scores) / len(scores)\n",
"        return round(max(0.0, min(100.0, 50.0 + avg * 50.0)), 1)\n",
"    except Exception:\n",
"        return 50.0\n",
"\n",
"def agent_risk(issue, listing, sub):\n",
"    s  = 50.0\n",
"    lg = (listing - issue) / issue * 100\n",
"    if lg > 30: s += 15\n",
"    elif lg > 10: s += 8\n",
"    elif lg > 0: s += 3\n",
"    elif lg < -15: s -= 20\n",
"    elif lg < -5: s -= 12\n",
"    else: s -= 6\n",
"    if sub > 100: s += 10\n",
"    elif sub > 50: s += 6\n",
"    elif sub > 10: s += 3\n",
"    elif sub < 2: s -= 8\n",
"    return round(max(0.0, min(100.0, s)), 1)\n",
"\n",
"def agent_ipo(issue, listing, sub, qib):\n",
"    s  = 50.0\n",
"    lg = (listing - issue) / issue * 100\n",
"    if lg > 50: s += 12\n",
"    elif lg > 25: s += 8\n",
"    elif lg > 10: s += 5\n",
"    elif lg < -10: s -= 12\n",
"    elif lg < 0: s -= 6\n",
"    if qib > 100: s += 12\n",
"    elif qib > 50: s += 8\n",
"    elif qib > 20: s += 4\n",
"    elif qib < 5: s -= 8\n",
"    if sub > 50: s += 5\n",
"    elif sub > 20: s += 3\n",
"    elif sub < 2: s -= 5\n",
"    return round(max(0.0, min(100.0, s)), 1)\n",
"\n",
"def orchestrator(ps, ms, ss, rs, iis):\n",
"    return round(ps*0.20 + ms*0.15 + ss*0.20 + rs*0.20 + iis*0.25, 1)\n",
"\n",
"def to_signal(oc):\n",
"    if oc >= 80: return 'STRONG_BUY'\n",
"    if oc >= 65: return 'BUY'\n",
"    if oc >= 45: return 'HOLD'\n",
"    if oc >= 30: return 'SELL'\n",
"    return 'STRONG_SELL'\n",
"\n",
"# --- Apply to all IPOs -------------------------------------------------------\n",
"print('Computing agent scores for all IPOs...')\n",
"for i, row in df.iterrows():\n",
"    ps  = agent_price(row['issue'], row['listing'], row['sub'])\n",
"    ms  = agent_macro(row['date'])\n",
"    ss  = agent_sentiment(row['name'])\n",
"    rs  = agent_risk(row['issue'], row['listing'], row['sub'])\n",
"    iis = agent_ipo(row['issue'], row['listing'], row['sub'], row['qib'])\n",
"    oc  = orchestrator(ps, ms, ss, rs, iis)\n",
"    df.at[i, 'sc_price']  = ps\n",
"    df.at[i, 'sc_macro']  = ms\n",
"    df.at[i, 'sc_sent']   = ss\n",
"    df.at[i, 'sc_risk']   = rs\n",
"    df.at[i, 'sc_ipo']    = iis\n",
"    df.at[i, 'sc_orch']   = oc\n",
"    df.at[i, 'signal']    = to_signal(oc)\n",
"    df.at[i, 'win_90d']   = 1 if row['ret_90d'] > 0 else 0\n",
"    df.at[i, 'decision']  = ('INVEST' if oc>=80 else 'PARTIAL_INVEST' if oc>=65\n",
"                             else 'HOLD' if oc>=45 else 'EXIT' if oc>=30 else 'STRONG_EXIT')\n",
"\n",
"print('Signal distribution:')\n",
"print(df['signal'].value_counts().to_string())\n",
"print('Avg Orchestrator score: {:.1f}/100'.format(df['sc_orch'].mean()))\n",
"df[['name','sc_price','sc_macro','sc_sent','sc_risk','sc_ipo','sc_orch','signal','ret_90d']].round(1)\n",
]))

